spring.application.name=portail-agence

spring.datasource.url=jdbc:mysql://localhost:3306/portail_agence
spring.datasource.username=root
spring.datasource.password=Shiftlock55

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080